# Generated by Django 4.2 on 2023-06-16 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalProduct',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('model_products.product',),
        ),
    ]
