# Generated by Django 4.2 on 2023-06-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_products', '0002_digitalproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slud',
            field=models.SlugField(unique=True),
        ),
    ]
