# Generated by Django 4.2 on 2024-04-10 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_products', '0006_product_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DigitalProduct',
        ),
    ]
