# Generated by Django 4.2 on 2024-04-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_products', '0007_delete_digitalproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=450),
        ),
    ]
