# Generated by Django 4.2 on 2023-05-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dear_app', '0003_remove_user_shoping_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shoping_cart',
            field=models.TextField(blank=True, null=True),
        ),
    ]
