# Generated by Django 4.2 on 2023-05-18 02:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dear_app', '0005_remove_user_shoping_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shoping_cart',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
