# Generated by Django 4.2 on 2023-05-18 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dear_app', '0006_user_shoping_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shoping_cart',
        ),
    ]
