# Generated by Django 4.2 on 2023-05-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dear_app', '0007_remove_user_shoping_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shoping_cart',
            field=models.CharField(default=[['1', 4], ['3', 7], ['2', 5]], max_length=200),
            preserve_default=False,
        ),
    ]
