# Generated by Django 4.2 on 2023-06-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dear_app', '0008_user_shoping_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_market',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
