# Generated by Django 4.2 on 2023-06-05 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dear_app', '0009_user_id_market'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.JSONField()),
                ('color', models.CharField(max_length=100)),
                ('product_dimensions', models.JSONField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dear_app.market')),
            ],
        ),
    ]
