# Generated by Django 4.2 on 2023-06-07 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dear_app', '0010_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
