# Generated by Django 4.2 on 2023-06-08 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dear_app', '0013_product_price_product_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_dimensions',
        ),
    ]
