# Generated by Django 4.2 on 2023-06-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dear_app', '0014_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_dimensions',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
