# Generated by Django 4.2 on 2023-06-24 07:12

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dear_app', '0017_alter_product_color_alter_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Prducto nuevo', max_length=100)),
                ('price', models.FloatField(default=100)),
                ('description', models.CharField(default='On sale', max_length=100)),
                ('color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None)),
                ('product_dimensions', models.TextField(default='[("Altura":20),("Anchura": 5),("Longitud": 8)]')),
                ('slug', models.SlugField(blank=True, default='new-product')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dear_app.market')),
            ],
        ),
    ]
