# Generated by Django 4.2 on 2023-06-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sec_nm', models.CharField(max_length=50)),
                ('gm', models.EmailField(max_length=254)),
                ('psw', models.CharField(max_length=50)),
                ('ps_conf', models.CharField(max_length=50)),
            ],
        ),
    ]
